name: mc-server-installer
version: '8.2'
summary: Minecraft Server Downloader and Installer/Configuration Tool
description: |
    A Minecraft Server installer and configuration snap that downloads the latest .jar file 
    and allows you to start your server with the amount of RAM you choose. 
    
    Admins may now run custom MAX RAM settings! Minimum RAM requirements are 1024M, so please
    keep this in mind. Additionally, -Xmn values have been reduced to 128M to keep with current
    guidance. See: https://minecraft.gamepedia.com/Server/Requirements 
    
    You can also backup your entire server with option 10 in the menu. They are pushed to
    /home/user/ so that uninstalling the snap won't affect your backups. 

license: MIT

base: core20
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x

apps:
  mc-server-installer:
    command: mc-server-installer
    plugs:
      - network
      - home
      - network-bind

parts:
  mc-server-installer:
    source: https://github.com/kz6fittycent/mc-server-installer
    source-type: git
    plugin: nil
    
    build-packages:
      - openjdk-8-jre-headless
      - curl
      - sed
      - jq
      - nano
      - tar
    
    stage-packages:
      - openjdk-8-jre-headless
      - curl
      - sed
      - jq
      - nano
      - tar
      
    prime:
        - -usr/lib/jvm/java-*/lib/security/cacerts
        - -usr/lib/jvm/java-*/jre/lib/security/cacerts      

  publish:
    plugin: dump
    source: .
