#!/bin/sh

# ARCH VARIABLES

if [ "$SNAP_ARCH" = "amd64" ]; then
  ARCH="x86_64-linux-gnu"
elif [ "$SNAP_ARCH" = "armhf" ]; then
  ARCH="arm-linux-gnueabihf"
else
  ARCH="$SNAP_ARCH-linux-gnu"
fi

# DEFINE LATEST JAR
LATEST=`curl -fsSL 'https://launchermeta.mojang.com/mc/game/version_manifest.json' |jq -r '.latest.release'`

# DEFINE INSTALLED JAR
INSTALLED=`find -iname "$SNAP_USER_DATA/versions/*" | sort -n | tail -1 | cut -d "/" -f2`

# DEFINE URL
MANIFEST_URL=`curl -fsSL 'https://launchermeta.mojang.com/mc/game/version_manifest.json' |jq -r '.versions[] |select(.id=="'"$LATEST"'") |.url'`

# URL CONT'D
JAR_URL=`curl -fsSL "$MANIFEST_URL" |jq -r '.downloads.server.url'`

# java paths
export JAVA_HOME=$SNAP/usr/lib/jvm/java-1.21.0-openjdk-$SNAP_ARCH
export PATH=$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH

# Colors and font characteristics
RED="\e[0;91m"
BLUE="\e[0;94m"
BOLD="\e[1m"
RESET="\e[0m"

cd $SNAP_USER_DATA

clear

# START THE INSTALLER
echo "--------------------------------"
echo ""
echo " ${BOLD}Welcome to MC-SERVER-INSTALLER${RESET}"
echo ""
echo "--------------------------------"
sleep 1.0
echo "

"
echo "              ${BOLD}NOTE${RESET}"
echo "            --------"
echo "${RED}YOU MUST AGREE TO THE EULA PRIOR"
echo "    TO RUNNING THE SERVER"
echo "       FIRST TIME ONLY${RESET}"
echo ""
sleep 1.5

while [ answer != "0" ]  
do 
clear 

echo "------------------------------------------"
echo ""
echo "         MINECRAFT SERVER INSTALLER"
echo "                   MENU              "
echo ""
echo "------------------------------------------"
echo ""
if ${INSTALLED} != ${LATEST}
then
    echo "ATTENTION: A new version ${LATEST} is"
    echo "available for download!"
    echo "Select OPTION 1 to get it."
else
    echo "You're running the latest version (${LATEST})"
fi
echo ""
echo "Select from the following options: " 
echo ""
echo "1) Download latest (v${LATEST}) server.jar"
echo "2) Agree to the EULA"
echo "3) Edit the server.properties file"
echo "4) Run MC server with max 2GB of RAM"
echo "5) Run MC server with max 4GB of RAM"
echo "6) Run MC server with max 6GB of RAM"
echo "7) Run MC server with max 8GB of RAM"
echo "8) Run MC server with max 16GB of RAM"
echo "9) View README"
echo "10) Back up your world"
echo "11) Run custom RAM settings"
echo "12) Run custom jar file and RAM settings"
echo "13) Quit"
echo "" 
read -p "Choice: " answer 
clear
    case $answer in 
       1) echo "Downloading v${LATEST} server.jar..."
       echo "" 
       curl -so server.jar $JAR_URL 
       ;; 
       2) echo "Setting things up first..."
       echo ""
       echo "Agreeing to the EULA..."
       echo ""
       echo "Ignore any errors, as they are normal..."
       echo ""
       sleep 1.0 
       java -Xmx2048M -Xms128M -XX:+UseG1GC -jar server.jar nogui    
       echo ""
       sed -ie s/false/true/g eula.txt
       echo ""
       echo "Done!"
       echo ""
       ;; 
       3) echo "Opening the server.properties file..."
       echo ""
       nano server.properties
       echo ""
       ;;
       4) echo "Starting server with 2GB of RAM..."
       echo ""
       java -Xmx2048M -Xms128M -XX:+UseG1GC -jar server.jar nogui
       ;; 
       5) echo "Starting server with 4GB of RAM..."
       echo ""
       java -Xmx4096M -Xms128M -XX:+UseG1GC -jar server.jar nogui
       ;;
       6) echo "Starting server with 6GB of RAM..."
       echo ""
       java -Xmx6144M -Xms128M -XX:+UseG1GC -jar server.jar nogui       
       ;;
       7) echo "Starting server with 8GB of RAM..."
       echo ""
       java -Xmx8192M -Xms128M -XX:+UseG1GC -jar server.jar nogui       
       ;;
       8) echo "Starting server with 16GB of RAM..."
       echo ""
       java -Xmx16384M -Xms128M -XX:+UseG1GC -jar server.jar nogui
       ;;
       9) echo ""
          echo "MC-SERVER-INSTALLER is not an officially"
          echo "supported or licensed application of "
          echo "Mojang."
          echo ""
          echo "The first time you run the installer,"
          echo "you'll need to download the .jar file"
          echo "(i.e. select option #1)." 
          echo "Now you may select option 2 to agree to" 
          echo "the EULA. You will never have to do this"
          echo "again, unless you remove the snap."
          echo ""
          echo "       ${BOLD}${RED}NO. THIS WON'T BE CHANGED!" 
          echo "          BECAUSE LEGAL STUFF${RESET}"
          echo ""
          echo "After selecting option #2, you can proceed"
          echo "with choosing any of the other options or"
          echo "setting up your server's configuration"
          echo "which is located in:"
          echo "${BLUE}~/snap/mc-server-installer/current${RESET}"
          echo ""
          echo "Anytime you need to update the server.jar,"
          echo "just select option 1 again. No need to agree"
          echo "to the EULA"
          echo ""
          echo "This snap package was built from scratch"
          echo "with an MIT License, by kz6fittycent:"
          echo ""
          echo "${BLUE}github.com/kz6fittycent/mc-server-installer${RESET}"
          echo ""
          ;;
       10) echo ""
           echo "Backing everything up..."
           echo ""
           sleep .5
           tar -cvzf /home/$USER/mc-server-installer_backup.tar.gz /home/$USER/snap/mc-server-installer/current/*
           echo ""
           echo "${BOLD}${BLUE}Your backup is now located in /home/$USER${RESET}"
           echo ""
           sleep 1.5
           ;;
       11) echo ""
           echo "You ${BOLD}MUST${RESET} follow the format outlined here:"
           echo "${BLUE}https://minecraft.gamepedia.com/Server/Requirements${RESET}"
           echo ""
           echo "(e.g. 4096M). You only need to enter the value, not"
           echo "the full java command. So, just 4096M or 8192M as a"
           echo "value, or whatever you want your MAX value to be." 
           echo "If you see errors, just double-check your entry"
           echo ""
           echo "ONLY MAX RAM SETTINGS ARE APPLIED!"
           echo ""
           echo "Minimum REQUIRED RAM is 1024M!"
           echo ""
           sleep 3
           
           read -p "Enter your MAX RAM settings: " RAM
           echo ""
           echo "Running your server with MAX ${RAM}..."
           echo ""
           sleep .5
           java -Xmx${RAM} -Xms128M -XX:+UseG1GC -jar server.jar nogui
           ;;  
       12) echo ""
           echo "You ${BOLD}MUST${RESET} provide the full path to your jar file!"
           echo "e.g. /home/$USER/custom_jar.jar"
           echo ""  
           sleep 3           
           read -p "Enter the location of your custom jar file (e.g. /home/$USER/server.jar): " JAR
           echo ""

           sleep .5
           echo ""
           echo "Set MAX RAM Values"
           echo ""
           echo "You ${BOLD}MUST${RESET} follow the format outlined here:"
           echo "${BLUE}https://minecraft.gamepedia.com/Server/Requirements${RESET}"
           echo ""
           echo "(e.g. 4096M). You only need to enter the value, not"
           echo "the full java command. So, just 4096M or 8192M as a"
           echo "value, or whatever you want your MAX value to be." 
           echo "If you see errors, just double-check your entry"
           echo ""
           echo "ONLY MAX RAM SETTINGS ARE APPLIED!"
           echo ""
           echo "Minimum REQUIRED MAX RAM entry is 1024M!"
           echo ""
           sleep 3
           
           read -p "Enter your MAX RAM settings: " RAM2
           echo ""
           echo "Running your custom MC server.jar with MAX ${RAM}..."
           echo ""
           sleep .5
           java -Xmx${RAM2} -Xms128M -XX:+UseG1GC -jar ${JAR} nogui
           ;;            
       13) break ;; 
   esac  
   echo "press RETURN for menu" 
   read key 
done 
exit 0
